<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="/assets/checkout/css/style.css">
        <script type="text/javascript" src="/assets/checkout/js/custom.js"></script>
        <link href='https://css.gg/arrow-left.css' rel='stylesheet'>
        <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/css/intlTelInput.css"/>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.8/js/intlTelInput.min.js"></script>
    </head>

    <body>
        <section id="timer">
            <div class="t-container">
                <div class="t-clock">00 : 00 : 00</div>
                <div class="t-div">
                    <p class="incon-t-clock">
                        <img src="/assets/checkout/img/clock.png"></span>
                    </p>
                    <p class="t-text">Contagem zerada</p>
                </div>
            </div>
        </section>

        <section id="checkout">
            <div class="d-flex-column">
            <div class="container">   
                <div class="parent">
                    <div class="div1">
                        <p class="div1-text">
                            O que você precisa saber para iniciar o curso:
                        </p>
                    </div>

                    <div class="div2">
                        <div class="curso">
                            <div class="info-curso">
                                <div class="icon-info">
                                    <span><img src="/assets/checkout/img/icons/icon-mail-void.png"></span>
                                </div>
                                <div class="info-description">
                                    <p class="info-title">Acesso via E-mail</p>
                                    <p class="info-text">Acesso ao produto liberado via e-mail. Rápido e descomplicado
                                    </p>
                                </div>
                            </div>
                            <div class="info-curso">
                                <div class="icon-info">
                                    <span><img src="/assets/checkout/img/icons/icon-segura-void.png"></span>
                                </div>                                
                                <div class="info-description">
                                    <p class="info-title">Compra segura
                                    </p>
                                    <p class="info-text">Ambiente seguro e autenticado</p>  
                                </div>
                            </div>
                            <div class="info-curso">
                                <div class="icon-info">
                                    <span><img src="/assets/checkout/img/icons/icon-check-void.png"></span>
                                </div>                                
                                <div class="info-description">
                                    <p class="info-title">Conteúdo Aprovado</p>
                                    <p class="info-text">100% revisado e aprovado</p>
                                </div>
                            </div>
                    </div>
                    </div>

                    <div class="div3">                 
                        <div id="main-course">
                            <div class="img-course">
                                <img class ="imagem" src="/uploads/<?=$this->escapeHtml($this->checkouts->getImagem())?>">
                            </div>
                            <div class="content-course">
                                <h2 class="course-title"><?= $this->escapeHtml($this->checkouts->getTitulo())?></h2>   
                                <p class="course-text">
                                    Autor: Curso Beta 
                                </p>   
                                <p class="course-price">
                                    12x de R$79,70
                                </p> 
                            </div>
                        </div>

                        <div id="dados-pessoais">
                            <form>
                                <div id="step-one">
                                    <div class="field-input">
                                        <label class="label" for="nome">Nome completo</label>
                                        <input type="text" id="nome" name="nome" placeholder="Digite seu nome completo">
                                    </div>
                                    <div class="field-input">
                                        <label class="label"for="email">Seu email</label>
                                        <input type="text" id="email" name="lastname" placeholder="Digite seu email para receber a compra">
                                    </div>
                                    <div class="field-input mb-1">
                                        <label class="label" for="celular">Celular</label>
                                        <input type="text" id="celular" name="celular" placeholder="Digite o número do seu celular">
                                    </div>
                                    <br>
                                </div>
                            </form>
                        </div>

                        <div id="pagamento">
                            <form>
                                <div class="row-pagamento">
                                    <div id="options" class="field-input d-flex">
                                        <input type="radio" id="credito" name="pagamento" value="1" checked>
                                        <label for="credito">Cartão de cŕedito</label>

                                        <input type="radio" id="boleto" name="pagamento" value="2">
                                        <label for="boleto">Boleto</label>

                                        <input type="radio" id="pix" name="pagamento" value="3">
                                        <label for="pix">PIX</label>

                                        <input type="radio" id="vermais" name="pagamento" value="4">
                                        <label for="vermais">Ver mais</label>
                                    </div>
                                    <div>
                                        <p></p>
                                    </div>
                                </div>
                                    <div id="form-credito" class="forma-pagamento">
                                        <div class="column-pagamento">
                                            <div class="input-pagamento">
                                                <div class="field-input">
                                                    <label class="label" for="numero-cartao" >Número do Cartão</label>
                                                    <input type="text" id="numero-cartao" name="numero" maxlength="19" placeholder="Digite somente números">
                                                </div>

                                                <div class="field-input">
                                                    <label class="label"for="titular">Nome do titular</label>
                                                    <input type="text" id="titular" maxlength="26" name="titular" placeholder="Digite o nome impresso no cartão">
                                                </div>

                                                <div class="field-input">
                                                    <label class="label" for="cpf">CPF/CNPJ (Titular do cartão)</label>
                                                    <input type="text" id="cpf" name="cpf" placeholder="Digite o número do seu CPF ou CNPJ">
                                                </div>

                                                <div class="infos-cartao">
                                                    <div class="field-input">
                                                        <label class="label" for="mes">Mẽs</label>
                                                        <input type="text" id="mes" maxlength="2" name="mes" placeholder="Mês">
                                                    </div>

                                                    <div class="field-input">
                                                        <label class="label" for="ano">Ano</label>
                                                        <input type="text" id="ano" maxlength="2" name="ano" placeholder="Ano">
                                                    </div>

                                                    <div class="field-input">
                                                        <label class="label" for="cvv">CVV</label>
                                                        <input type="text" id="cvv" maxlength="3" name="cvv" placeholder="CVV">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="cartao">
                                                <div class="img-cartao">
                                                    <p>chipe aqui</p>
                                                    <div class="cartao-infos">
                                                        <p class="cartao-numero cartao-estilo">**** **** **** ****</p>
                                                        <p class="cartao-nome cartao-estilo">**** * * *****</p>
                                                        <div class="cartao-detalhes">
                                                            <div>
                                                                <p class="cartao-data-title">val:</p>
                                                                <p class="cartao-data cartao-estilo">
                                                                    <span class="cartao-mes">00</span>/<span class="cartao-ano">00</span>
                                                                </p>
                                                            </div>
                                                            <div>
                                                                <p class="cartao-cvv-title">cvv</p>
                                                                <p class="cartao-cvv cartao-estilo">000</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="tipos-cartoes">
                                                    <p> <img src="/assets/checkout/img/logo-master.png" alt=""></p>
                                                    <p> <img src="/assets/checkout/img/logo-visa.png" alt=""></p>
                                                    <p> <img class="d-flex" src="/assets/checkout/img/logo-elo.png" alt=""></p>
                                                    <p> <img src="/assets/checkout/img/logo-amex.png" alt=""></p>
                                                </div>
                                            </div>
                                        </div>
                                        
                                        <div class="field-input parcelas">
                                            <label class="label" for="telefone">Selecione o número de parcelas</label>
                                            <select id="country" name="country">
                                                <option value="option1">12x de R$79,70*</option>
                                                <option value="option2">12x de R$79,70*</option>
                                                <option value="option3">12x de R$79,70*</option>
                                            </select>
                                        </div>
                                    </div>

                                    <div id="form-boleto" class="forma-pagamento">
                                        <div class="column-pagamento">
                                            <div class="input-pagamento">
                                                <div class="field-input">
                                                    <label class="label" for="numero">Boleto</label>
                                                    <input type="text" id="numero" name="numero" placeholder="Digite somente números">
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div id="form-pix" class="forma-pagamento">
                                        <div class="column-pagamento">
                                            <div class="input-pagamento">
                                                <div class="field-input">
                                                    <label class="label" for="numero">PIX</label>
                                                    <input type="text" id="numero" name="numero" placeholder="Digite somente números">
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div id="form-outros" class="forma-pagamento">
                                        <div class="column-pagamento">
                                            <div class="input-pagamento">
                                                <div class="field-input">
                                                    <label class="label" for="numero">Outros</label>
                                                    <input type="text" id="numero" name="numero" placeholder="Digite somente números">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                            </form>
                        </div>

                        <div class="details-compras">Detalhes da compra</div>
                        <div class="price-final">
                            <p class="price-text">Perícia Judicial</p>
                            <div class="prive-valor">12x de R$ 59,70*</div>
                        </div>
                        <button class="button c-pointer" type="submit" value="Comprar Agora">COMPRAR AGORA</button>
                        <div id="selos" class="text-center">
                            <img src="/assets/checkout/img/icons/compra.png">
                            <img src="/assets/checkout/img/icons/privacidade.png">
                            <img src="/assets/checkout/img/icons/garantia.png">
                        </div>
                        <div id="selos-mobile" class="text-center">
                            <img src="/assets/checkout/img/mob-compra.png">
                            <img src="/assets/checkout/img/mob-privacidade.png">
                            <img src="/assets/checkout/img/mob-garantia.png">
                        </div>
                    </div> 

                    <div class="div4"> 
                        <div class="course-resource">
                            <div class="resource-title">
                                <span></span>
                                <h2 class="cr-title">Resumo do curso</h2>
                            </div>
                            <div class="teste">
                                <div class="resource">
                                    <p class="ul-cr-title">Curso de Perícia Judicial:</p>
                                    <ul>
                                        <p class="li-resource">
                                            <?= $this->escapeHtml($this->checkouts->getDescricao())?>
                                        </p>
                                    </ul>
                                </div>
                                <div class="resource">
                                    <p class="ul-cr-title">+ 5 Bônus</p>
                                    <ul>
                                        <li class="li-resource">
                                            Curso de AssistenteTécnico Judicial
                                        </li>
                                        <li class="li-resource">
                                            Passo a passo da Perícia Judicial
                                        </li>
                                        <li class="li-resource">
                                            Pacote de laudos e petições
                                        </li>
                                        <li class="li-resource">
                                            Tutoria especializada
                                        </li>
                                        <li class="li-resource">
                                            Grupo VIP para Peritos Judiciais
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div>
                                <span></span>
                                <h2 class="aprender">O que você vai aprender?</h2>
                            </div>

                            <div class="aprendizados">
                                <?php
                                    $items = explode(",", $this->checkouts->getitemAprendizado());
                                    foreach($items as $item){?>
                                        <div class="item-aprendizados">
                                            <span><img src="/assets/checkout/img/icons/icon-check.png"></span>
                                            <p> 
                                                <?= trim($item); ?>
                                            </p>
                                        </div>
                                    <?php }  
                                ?>
                                <div class="item-aprendizados">
                                    <span><img src="/assets/checkout/img/icons/icon-check.png"></span>
                                    <p>Ganhar uma renda extra de R$1.200 a R$12.000 em média, trabalhando de casa e com horário flexível
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="learn">

                        </div>
                    </div>
                </div>
                <footer>
                     <div id="footer" class="text-left">
                        <div class="row-footer row2 ">
                              <div class="md-col mb-1 mg-0-8">
                                <p class="f-title">Satisfação garantida ou o seu dinheiro de volta</p>
                                <p class="f-descricao">
                                     Garantia incondicional em até 7 dias você efetuar o <br> 
                                     cancelamento e nós devolvemos 100% do valor pago.
                                </p>
                            </div>
                            <div class="md-col mb-1 mg-0-8">
                                <p class="f-title">Precisa de ajuda?</p>
                                <p class="f-descricao">
                                    Vale com a gente via WhatsApp ou e-mail.<br> 
                                    Nosso site utiliza cookies. Para saber mais, confira a nossa 
                                    política de privacidade e ostermos de compra.
                                </p>
                            </div>
                            <div class="md-col">
                                <img src="/assets/checkout/img/reclameaqui.png">
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        </section>
        <script src="./js/formularioDinamico.js"></script>
        <script src="./js/telfone.js"></script>
    <body>
</html> 
    