<?php
    $title = 'Adicionar Novo Produto';
    $this->headTitle($title);
?> 
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
    $nome = $form->get('nome');
    $nome->setAttribute('class', 'form-control');
    $nome->setAttribute('placeholder', 'Nome');

    $descricao = $form->get('descricao');
    $descricao->setAttribute('class', 'form-control');
    $descricao->setAttribute('placeholder', 'Descrição');

    $imagem = $form->get('imagem');
    $imagem->setAttribute('class', 'form-control');
    $imagem->setAttribute('placeholder', 'Imagem');

    $submit = $form->get('submit');
    $submit->setAttribute('class', 'btn btn-primary');

    $form->setAttribute('action', $this->url('produto', ['action' => 'add']));
    $form->prepare();

    echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($nome) ?>
    <?= $this->formElement($nome) ?>
    <?= $this->formElementErrors()->render($nome, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($descricao) ?>
    <?= $this->formElement($descricao) ?>
    <?= $this->formElementErrors()->render($descricao, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($imagem) ?>
    <?= $this->formElement($imagem) ?>
    <?= $this->formElementErrors()->render($imagem, ['class' => 'help-block']) ?>
</div>


<?php
    echo $this->formSubmit($submit);
    echo $this->formHidden($form->get('id'));
    echo $this->form()->closeTag();