<h1>Exclusão de Checkout</h1>

<p>Você tem certeza que quer excluir este checkout?</p>

<ul class="list-group">
    <li class="list-group-item"><?= $this->escapeHtml($this->checkout->getTitulo()) ?></li>
</ul>

<form action="<?php $this->url('checkout/delete', [], true) ?>" method="post">
    <input type="hidden" name="id" value="<?= $this->escapeHtmlAttr($this->checkout->getId()) ?>" />
    <input class="btn btn-default" type="submit" name="confirm" value="Cancel" />
    <input class="btn btn-danger" type="submit" name="confirm" value="Delete" />
</form>