<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-4">Novo Checkout</h1>
    <p></p>
    <hr class="my-4">
    <a class="btn btn-primary btn-lg" href="/checkout" target="_blank">
       Gerenciar &raquo;
    </a>
</div>

<div class="card-deck">
    <div class="card">
        <h2 class="card-header">Checkout</h2>
        <div class="card-body">
            <p></p>
            <a class="btn btn-primary" href="/checkout">
                Gerenciar Checkout's  &raquo;
            </a>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header">Pacotes</h2>
        <div class="card-body">
            <p> </p>
            <a class="btn btn-primary" href="/produto">
                Gerenciar Pacotes &raquo;
            </a>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header">Produtos</h2>
        <div class="card-body">
            <p> </p>
            <a class="btn btn-primary" href="/produto">
                Gerenciar Produtos &raquo;
            </a>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header">Vendas</h2>
        <div class="card-body">
            <p></p>
            <a class="btn btn-primary" href="/produto">
               Gerenciar Vendas &raquo;
            </a>
        </div>
    </div>
</div>